# Configure.
language: python
python: 3.4
sudo: false

# Run.
install: pip install appveyor-artifacts coveralls tox
script: tox -e lint,py34,py33,pypy,py27,docs
after_success:
  - mv .coverage .coverage.travis
  - appveyor-artifacts -mi download
  - coverage combine
  - coveralls
  - touch docs/key; chmod 600 docs/key  # Secure before storing key data.
  - openssl aes-256-cbc -K $encrypted_1b7c54115a3f_key -iv $encrypted_1b7c54115a3f_iv -in docs/key.enc -out docs/key -d
  - eval `ssh-agent -s`; ssh-add docs/key
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git remote set-url origin "git@github.com:$TRAVIS_REPO_SLUG"
  - export ${!TRAVIS*}  # For commit messages.
  - tox -e docsV
